# Generated by Django 4.2.2 on 2023-12-14 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False, verbose_name='id_tipo')),
                ('tipo_usuario', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Usuario')),
                ('nombre_usuario', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre del Usuario')),
                ('pass_usuario', models.CharField(blank=True, max_length=128, null=True)),
                ('pnombre', models.CharField(blank=True, max_length=30, null=True)),
                ('ppaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('rut', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('num_casa', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(db_column='Patente', max_length=9, primary_key=True, serialize=False, verbose_name='Patente del Vehiculo')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca del Vehiculo')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo  del Vehiculo')),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('nombre_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario', to_field='nombre_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id_estacionamiento', models.AutoField(primary_key=True, serialize=False, verbose_name='id_estacionamiento')),
                ('costo', models.IntegerField(blank=True, null=True)),
                ('espacio', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_usuario_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_nombre_usuario_cliente', to='core.usuario', to_field='nombre_usuario', verbose_name='Nombre Cliente')),
                ('nombre_usuario_duenno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_nombre_usuario_duenno', to='core.usuario', to_field='nombre_usuario', verbose_name='Nombre Dueño')),
                ('patente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
    ]
