# Generated by Django 4.2.2 on 2023-11-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False, verbose_name='id_tipo')),
                ('tipo_usuario', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('pass_usuario', models.CharField(blank=True, max_length=15, null=True)),
                ('pnombre', models.CharField(blank=True, max_length=30, null=True)),
                ('ppaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('rut', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('num_casa', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
