# Generated by Django 4.2.2 on 2023-12-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='ubicación',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='patente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
