# Generated by Django 4.2.2 on 2023-12-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estacionamiento_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacionamiento',
            old_name='ubicación',
            new_name='ubicacion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='patente_vehiculo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
